spring:
  # General
  main:
    banner-mode: off

  # Database
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    generate-ddl: ${JPA_GENERATE_DDL:false}

logbook:
  json-path-exclusion-filters: '{"$.attachments[*].content": "[base64]", "$.attachments[*].base64Data": "[base64]"}'

# Defaults
messaging:
  defaults:
    sms:
      name: ${DEFAULT_SENDER_SMS_NAME}
    email:
      name: ${DEFAULT_SENDER_EMAIL_NAME}
      address: ${DEFAULT_SENDER_EMAIL_ADDRESS}
    digital-mail:
      municipality-id: ${DIGITAL_MAIL_SENDER_DEFAULT_MUNICIPALITY_ID}
      subject: ${DIGITAL_MAIL_SENDER_DEFAULT_SUBJECT}
      support-info:
        text: ${DIGITAL_MAIL_SENDER_DEFAULT_SUPPORT_INFO_TEXT}
        email-address: ${DIGITAL_MAIL_SENDER_DEFAULT_SUPPORT_INFO_EMAIL_ADDRESS}
        phone-number: ${DIGITAL_MAIL_SENDER_DEFAULT_SUPPORT_INFO_PHONE_NUMBER}
        url: ${DIGITAL_MAIL_SENDER_DEFAULT_SUPPORT_INFO_URL}

integration:
  # SmsSender integration
  sms-sender:
    base-url: ${SMS_SENDER_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${SMS_SENDER_INTEGRATION_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # EmailSender integration
  email-sender:
    base-url: ${EMAIL_SENDER_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # WebMessageSender integration
  web-message-sender:
    base-url: ${WEB_MESSAGE_SENDER_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # DigitalMailSender integration
  digital-mail-sender:
    base-url: ${DIGITAL_MAIL_SENDER_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # SnailmailSender integration
  snailmail-sender:
    base-url: ${SNAILMAIL_SENDER_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # FeedbackSettings integration
  feedback-settings:
    base-url: ${FEEDBACK_SETTINGS_INTEGRATION_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}
