spring:
  # General
  main:
    banner-mode: off

  # Database
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    generate-ddl: ${JPA_GENERATE_DDL:false}

logbook:
  exclusionfilters:
    json-path: '{"$.attachments[*].content": "[base64]", "$.attachments[*].base64Data": "[base64]", "$.attachments[*].body": "[base64]"}'

messaging:
  defaults:
    sms:
      name: ${DEFAULT_SMS_SENDER_NAME}
    email:
      name: ${DEFAULT_EMAIL_SENDER_NAME}
      address: ${DEFAULT_EMAIL_SENDER_ADDRESS}
    digital-mail:
      municipality-id: ${DEFAULT_DIGITAL_MAIL_SENDER_MUNICIPALITY_ID}
      subject: ${DEFAULT_DIGITAL_MAIL_SENDER_SUBJECT}
      support-info:
        text: ${DEFAULT_DIGITAL_MAIL_SENDER_SUPPORT_INFO_TEXT}
        email-address: ${DEFAULT_DIGITAL_MAIL_SENDER_SUPPORT_INFO_EMAIL_ADDRESS}
        phone-number: ${DEFAULT_DIGITAL_MAIL_SENDER_SUPPORT_INFO_PHONE_NUMBER}
        url: ${DEFAULT_DIGITAL_MAIL_SENDER_SUPPORT_INFO_URL}

integration:
  # SmsSender integration
  sms-sender:
    base-url: ${INTEGRATION_SMS_SENDER_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # EmailSender integration
  email-sender:
    base-url: ${INTEGRATION_EMAIL_SENDER_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # WebMessageSender integration
  web-message-sender:
    base-url: ${INTEGRATION_WEB_MESSAGE_SENDER_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # DigitalMailSender integration
  digital-mail-sender:
    base-url: ${INTEGRATION_DIGITAL_MAIL_SENDER_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # SnailmailSender integration
  snailmail-sender:
    base-url: ${INTEGRATION_SNAILMAIL_SENDER_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}

  # FeedbackSettings integration
  feedback-settings:
    base-url: ${INTEGRATION_FEEDBACK_SETTINGS_BASE_URL}
    token-url: ${OAUTH2_TOKEN_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}
