spring:
  # No banner
  main:
    banner-mode: off

  # Disable Flyway
  flyway:
    enabled: false

  # Database
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  jpa:
    show-sql: false
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
            create-source: metadata
      hibernate:
        show-sql: false
        hbm2ddl:
          schema-generation:
            script:
              append: false
        format_sql: true

# Silence some logs
logging:
  level:
    com.tngtech.archunit: INFO

# Defaults
messaging:
  defaults:
    sms:
      name: Sender
    email:
      name: Longer Sender
      address: longer.sender@somehost.com
    digital-mail:
      municipality-id: someMunicipalityId
      subject: someSubject
      support-info:
        text: someInfoText
        email-address: someone@something.com
        phone-number: somePhoneNumber
        url: someUrl

integration:

  # OepIntegrator integration
  oep-integrator:
    base-url: http://oep-integrator/api
    token-url: http://oep-integrator/token
    client-id: someClientId
    client-secret: someClientSecret

  # SmsSender integration
  sms-sender:
    base-url: http://sms-sender/api
    token-url: http://sms-sender/token
    client-id: someClientId
    client-secret: someClientSecret

  # EmailSender integration
  email-sender:
    base-url: http://email-sender/api
    token-url: http://email-sender/token
    client-id: someClientId
    client-secret: someClientSecret

  # WebMessageSender integration
  web-message-sender:
    base-url: http://web-message-sender/api
    token-url: http://web-message-sender/token
    client-id: someClientId
    client-secret: someClientSecret

  # DigitalMailSender integration
  digital-mail-sender:
    base-url: http://digital-mail-sender/api
    token-url: http://digital-mail-sender/token
    client-id: someClientId
    client-secret: someClientSecret

  # SnailmailSender integration
  snailmail-sender:
    base-url: http://snailmail-sender/api
    token-url: http://snailmail-sender/token
    client-id: someClientId
    client-secret: someClientSecret

  # ContactSettings integration
  contact-settings:
    base-url: http://contact-settings/api
    token-url: http://contact-settings/token
    client-id: someClientId
    client-secret: someClientSecret

  # Party integration
  party:
    base-url: http://party/api
    token-url: http://party/token
    client-id: someClientId
    client-secret: someClientSecret

  # Citizen integration
  citizen:
    base-url: http://citizen/api
    token-url: http://citizen/token
    client-id: someClientId
    client-secret: someClientSecret
