openapi: 3.0.1
info:
  title: Digital Mail Sender
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "4.0"
servers:
  - url: http://127.0.0.1:8080
    description: Generated server url
paths:
  /{municipalityId}/{organizationNumber}/send-digital-mail:
    post:
      tags:
        - Digital Mail
      summary: Send a digital mail
      operationId: sendDigitalMail
      parameters:
        - name: municipalityId
          in: path
          description: Municipality id
          required: true
          schema:
            type: string
          example: 2281
        - name: organizationNumber
          in: path
          description: The organization number of the sending organization
          required: true
          schema:
            type: string
          example: 5561234567
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DigitalMailRequest"
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DigitalMailResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Problem"
                  - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /{municipalityId}/{organizationNumber}/mailboxes:
    post:
      tags:
        - Digital Mail
      summary: "Retrieve a list of mailboxes. Contains partyId, supplier and if the\
        \ mailbox is reachable for the given organization."
      operationId: hasAvailableMailboxes
      parameters:
        - name: municipalityId
          in: path
          description: Municipality id
          required: true
          schema:
            type: string
          example: 2281
        - name: organizationNumber
          in: path
          description: The organization number of the intended sending organization
          required: true
          schema:
            type: string
          example: 5561234567
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mailbox"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Problem"
                  - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /{municipalityId}/send-digital-invoice:
    post:
      tags:
        - Digital Mail
      summary: Send a digital invoice
      operationId: sendDigitalInvoice
      parameters:
        - name: municipalityId
          in: path
          description: Municipality id
          required: true
          schema:
            type: string
          example: 2281
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DigitalInvoiceRequest"
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DigitalInvoiceResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Problem"
                  - $ref: "#/components/schemas/ConstraintViolationProblem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /api-docs:
    get:
      tags:
        - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    Attachment:
      required:
        - body
        - contentType
        - filename
      type: object
      properties:
        contentType:
          type: string
          description: "Allowed type is: application/pdf"
          example: application/pdf
        body:
          minLength: 1
          type: string
          description: BASE64-encoded body
        filename:
          minLength: 1
          type: string
          description: The name of the file
          example: sample.pdf
      description: A PDF file/attachment
    BodyInformation:
      required:
        - contentType
      type: object
      properties:
        contentType:
          type: string
          description: "The content type for the message, text/plain for only text,\
            \ text/html for HTML messages."
          example: text/html
        body:
          type: string
          description: Plain-text body
      description: The body of the message
    DigitalMailRequest:
      required:
        - headerSubject
        - municipalityId
        - partyId
        - supportInfo
      type: object
      properties:
        partyId:
          type: string
          description: partyId for the person or organization the digital mail should
            be sent to
          example: 6a5c3d04-412d-11ec-973a-0242ac130003
        municipalityId:
          type: string
          description: MunicipalityId
          example: "2281"
        headerSubject:
          minLength: 1
          type: string
          description: The subject of the digital mail.
          example: Viktig information från Sundsvalls kommun
        supportInfo:
          $ref: "#/components/schemas/SupportInfo"
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/Attachment"
        bodyInformation:
          $ref: "#/components/schemas/BodyInformation"
      description: The body of the digital mail request
    SupportInfo:
      required:
        - supportText
      type: object
      properties:
        supportText:
          minLength: 1
          type: string
          description: Information text describing the different ways the recipient
            may contact the sender.
          example: Kontakta oss via epost eller telefon.
        contactInformationUrl:
          type: string
          description: Url where the recipient may find more information.
          example: https://sundsvall.se/
        contactInformationPhoneNumber:
          type: string
          description: Phone number the recipient may call to get in contact with
            the sender.
          example: "4660191000"
        contactInformationEmail:
          type: string
          description: Email address the recipient may use to get in contact with
            the sender.
          example: sundsvalls.kommun@sundsvall.se
      description: Contains contact information and where the recipient may turn to
        for questions.
    Problem:
      type: object
      properties:
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        title:
          type: string
        detail:
          type: string
        status:
          $ref: "#/components/schemas/StatusType"
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    ConstraintViolationProblem:
      type: object
      properties:
        cause:
          $ref: "#/components/schemas/ThrowableProblem"
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        type:
          type: string
          format: uri
        status:
          $ref: "#/components/schemas/StatusType"
        violations:
          type: array
          items:
            $ref: "#/components/schemas/Violation"
        title:
          type: string
        message:
          type: string
        instance:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        detail:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    ThrowableProblem:
      type: object
      properties:
        cause:
          $ref: "#/components/schemas/ThrowableProblem"
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        message:
          type: string
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        title:
          type: string
        detail:
          type: string
        status:
          $ref: "#/components/schemas/StatusType"
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    DeliveryStatus:
      type: object
      properties:
        delivered:
          type: boolean
        partyId:
          type: string
        transactionId:
          type: string
    DigitalMailResponse:
      type: object
      properties:
        deliveryStatus:
          $ref: "#/components/schemas/DeliveryStatus"
    Mailbox:
      type: object
      properties:
        partyId:
          type: string
          description: partyId for the person the mailbox belongs to
        supplier:
          type: string
          description: "Name of the mailbox, e.g. Kivra"
        reachable:
          type: boolean
          description: If it's possible to send messages to this mailbox
      description: Response model for a mailbox
    Details:
      required:
        - accountNumber
        - accountType
        - amount
        - dueDate
        - paymentReference
        - paymentReferenceType
      type: object
      properties:
        amount:
          type: number
          description: The invoice amount
          format: float
          example: 123.45
        dueDate:
          type: string
          description: The invoice due date
          format: date
          example: 2023-10-09
        paymentReferenceType:
          type: string
          description: The payment reference type
          example: SE_OCR
          enum:
            - SE_OCR
            - TENANT_REF
        paymentReference:
          maxLength: 25
          minLength: 1
          type: string
          description: The payment reference number
          example: "426523791"
        accountType:
          type: string
          description: The receiving account type
          example: BANKGIRO
          enum:
            - BANKGIRO
            - PLUSGIRO
        accountNumber:
          type: string
          description: The receiving account (a valid BANKGIRO or PLUSGIRO number)
          example: "12345"
      description: Invoice details
    DigitalInvoiceRequest:
      required:
        - details
        - files
        - partyId
        - subject
        - type
      type: object
      properties:
        partyId:
          type: string
          description: partyId for the person or organization the invoice should be
            sent to
          example: 6a5c3d04-412d-11ec-973a-0242ac130003
        type:
          type: string
          description: Invoice type
          example: INVOICE
          default: INVOICE
          enum:
            - INVOICE
            - REMINDER
        subject:
          minLength: 1
          type: string
          description: The invoice subject
          example: Faktura från Sundsvalls kommun
        reference:
          type: string
          description: Invoice reference
          example: "Faktura #12345"
        payable:
          type: boolean
          description: Whether the invoice is payable
          default: true
        details:
          $ref: "#/components/schemas/Details"
        files:
          minItems: 1
          type: array
          items:
            $ref: "#/components/schemas/Attachment"
    DigitalInvoiceResponse:
      type: object
      properties:
        partyId:
          type: string
        sent:
          type: boolean
  securitySchemes: {}