openapi: 3.0.1
info:
  title: Digital Mail Sender
  contact: { }
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "2.2"
paths:
  /send-digital-mail:
    post:
      tags:
        - Digital Mail
      summary: Send a digital mail
      operationId: sendDigitalMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalMailRequest'
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalMailResponse'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/DigitalMailResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Problem'
                  - $ref: '#/components/schemas/ConstraintViolationProblem'
            application/problem+json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Problem'
                  - $ref: '#/components/schemas/ConstraintViolationProblem'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /send-digital-invoice:
    post:
      tags:
        - Digital Mail
      summary: Send a digital invoice
      operationId: sendDigitalInvoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalInvoiceRequest'
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalInvoiceResponse'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/DigitalInvoiceResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Problem'
                  - $ref: '#/components/schemas/ConstraintViolationProblem'
            application/problem+json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Problem'
                  - $ref: '#/components/schemas/ConstraintViolationProblem'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /has-available-mailbox/{partyId}:
    post:
      tags:
        - Digital Mail
      summary: Check if a party has a digital mailbox and if said party has chosen
        to receive digital mail
      operationId: hasAvailableMailbox
      parameters:
        - name: partyId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful Operation (available mailbox(es) found)
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not Found (no available mailbox(es) found)
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Problem'
  /api-docs:
    get:
      tags:
        - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    Problem:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            type: object
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
        status:
          $ref: '#/components/schemas/StatusType'
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    ConstraintViolationProblem:
      type: object
      properties:
        cause:
          $ref: '#/components/schemas/ThrowableProblem'
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        type:
          type: string
          format: uri
        status:
          $ref: '#/components/schemas/StatusType'
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'
        title:
          type: string
        message:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: object
        instance:
          type: string
          format: uri
        detail:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    ThrowableProblem:
      type: object
      properties:
        cause:
          $ref: '#/components/schemas/ThrowableProblem'
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              className:
                type: string
              nativeMethod:
                type: boolean
        message:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: object
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
        status:
          $ref: '#/components/schemas/StatusType'
        suppressed:
          type: array
          items:
            type: object
            properties:
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    className:
                      type: string
                    nativeMethod:
                      type: boolean
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    Attachment:
      required:
        - body
        - contentType
        - filename
      type: object
      properties:
        contentType:
          type: string
          description: "Allowed type is: application/pdf"
          example: application/pdf
        body:
          type: string
          description: BASE64-encoded body
        filename:
          type: string
          description: The name of the file
          example: sample.pdf
      description: A PDF file/attachment
    BodyInformation:
      required:
        - contentType
      type: object
      properties:
        contentType:
          type: string
          description: "The content type for the message, text/plain for only text,\
            \ text/html for HTML messages."
          example: text/html
        body:
          type: string
          description: Plain-text body
      description: The body of the message
    DigitalMailRequest:
      required:
        - headerSubject
        - municipalityId
        - partyId
        - supportInfo
      type: object
      properties:
        partyId:
          type: string
          description: partyId for the person or organization the digital mail should
            be sent to
          example: 6a5c3d04-412d-11ec-973a-0242ac130003
        municipalityId:
          type: string
          description: MunicipalityId
          example: "2281"
        headerSubject:
          type: string
          description: The subject of the digital mail.
          example: Viktig information från Sundsvalls kommun
        supportInfo:
          $ref: '#/components/schemas/SupportInfo'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        bodyInformation:
          $ref: '#/components/schemas/BodyInformation'
      description: The body of the digital mail request
    SupportInfo:
      required:
        - supportText
      type: object
      properties:
        supportText:
          type: string
          description: Information text describing the different ways the recipient
            may contact the sender.
          example: Kontakta oss via epost eller telefon.
        contactInformationUrl:
          type: string
          description: Url where the recipient may find more information.
          example: https://sundsvall.se/
        contactInformationPhoneNumber:
          type: string
          description: Phone number the recipient may call to get in contact with
            the sender.
          example: "4660191000"
        contactInformationEmail:
          type: string
          description: Email address the recipient may use to get in contact with
            the sender.
          example: sundsvalls.kommun@sundsvall.se
      description: Contains contact information and where the recipient may turn to
        for questions.
    DeliveryStatus:
      type: object
      properties:
        delivered:
          type: boolean
        partyId:
          type: string
        transactionId:
          type: string
    DigitalMailResponse:
      type: object
      properties:
        deliveryStatus:
          $ref: '#/components/schemas/DeliveryStatus'
    Details:
      required:
        - accountNumber
        - accountType
        - amount
        - dueDate
        - paymentReference
        - paymentReferenceType
      type: object
      properties:
        amount:
          type: number
          description: The invoice amount
          format: float
          example: 123.45
        dueDate:
          type: string
          description: The invoice due date
          format: date
          example: 2023-10-09
        paymentReferenceType:
          type: string
          description: The payment reference type
          example: SE_OCR
          enum:
            - SE_OCR
            - TENANT_REF
        paymentReference:
          maxLength: 25
          type: string
          description: The payment reference number
          example: "426523791"
        accountType:
          type: string
          description: The receiving account type
          example: BANKGIRO
          enum:
            - BANKGIRO
            - PLUSGIRO
        accountNumber:
          type: string
          description: The receiving account (a valid BANKGIRO or PLUSGIRO number)
          example: "12345"
      description: Invoice details
    DigitalInvoiceRequest:
      required:
        - details
        - files
        - partyId
        - subject
        - type
      type: object
      properties:
        partyId:
          type: string
          description: partyId for the person or organization the invoice should be
            sent to
          example: 6a5c3d04-412d-11ec-973a-0242ac130003
        type:
          type: string
          description: Invoice type
          example: INVOICE
          default: INVOICE
          enum:
            - INVOICE
            - REMINDER
        subject:
          type: string
          description: The invoice subject
          example: Faktura från Sundsvalls kommun
        reference:
          type: string
          description: Invoice reference
          example: "Faktura #12345"
        payable:
          type: boolean
          description: Whether the invoice is payable
          default: true
        details:
          $ref: '#/components/schemas/Details'
        files:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    DigitalInvoiceResponse:
      type: object
      properties:
        partyId:
          type: string
        sent:
          type: boolean
  securitySchemes: { }
