spring:
  # No banner
  main:
    banner-mode: off

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///

# Defaults
messaging:
  defaults:
    sms:
      name: Sender
    email:
      name: Longer Sender
      address: longer.sender@somehost.com
    digital-mail:
      municipality-id: someMunicipalityId
      subject: someSubject
      support-info:
        text: someInfoText
        email-address: someone@something.com
        phone-number: somePhoneNumber
        url: someUrl

integration:
  # SmsSender integration
  sms-sender:
    base-url: http://localhost:${wiremock.server.port}/sms-sender
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret

  # EmailSender integration
  email-sender:
    base-url: http://localhost:${wiremock.server.port}/email-sender
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret

  # SnailmailSender integration
  snailmail-sender:
    base-url: http://localhost:${wiremock.server.port}/snailmail-sender
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret

  # WebMessageSender integration
  web-message-sender:
    base-url: http://localhost:${wiremock.server.port}/web-message-sender
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret

  # DigitalMailSender integration
  digital-mail-sender:
    base-url: http://localhost:${wiremock.server.port}/digital-mail-sender
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret

  # Slack integration
  slack:
    base-url: http://localhost:${wiremock.server.port}/slack/

  # ContactSettings integration
  contact-settings:
    base-url: http://localhost:${wiremock.server.port}/contact-settings
    token-url: http://localhost:${wiremock.server.port}/token
    client-id: someClientId
    client-secret: someClientSecret
